name: ffl
encoder:
    type: UNetResNet101
    pretrained: true

    input_size: 512
    input_height: ${.input_size}
    input_width: ${.input_size}

    depth: 101
    num_filters: 32
    dropout_2d: 0.2
    is_deconv: False
    
    output_size: 512
    output_height: ${.output_size}
    output_width: ${.output_size}
    out_feature_channels: 32

compute_seg: True
compute_crossfield: True

seg_params:
    compute_interior: True
    compute_edge: False
    compute_vertex: False

loss:
  multiloss:
    normalization_params:
      min_samples: 10  # Per GPU
      max_samples: 1000  # Per GPU
    coefs:
      epoch_thresholds:
        - 0
        - 5
        - 10  # From 0 to 5: gradually go from coefs[0] to coefs[1] for list coefs
      seg: 10
      crossfield_align: 1
      crossfield_align90: 0.2
      crossfield_smooth: 0.005
      seg_interior_crossfield:
        - 0
        - 0
        - 0.2
      seg_edge_crossfield:
        - 0
        - 0
        - 0.2
      seg_edge_interior:
        - 0
        - 0
        - 0.2
  seg_loss_params:
    bce_coef: 1.0
    dice_coef: 0.2
    use_dist: false  # Dist weights as in the original U-Net paper
    use_size: false  # Size weights increasing importance of smaller buildings
    w0: 50  # From original U-Net paper: distance weight to increase loss between objects
    sigma: 10  # From original U-Net paper: distance weight to increase loss between objects

fusion: patch_concat # or feature_concat

# optimization

# training
batch_size: 32
start_epoch: 0
num_epochs: 300
milestone: 0
learning_rate: 1e-3
weight_decay: 0.0
gamma: 0.95

defaults:
    - lidar_encoder: pointpillars
    - polygonization: asm_acm

augmentations:
    # - D4
    - Resize

eval:
  test_time_augmentation: false # not actually used anywhere

  patch_size: null
  patch_overlap: 200

  seg_threshold: 0.5

  save_individual_outputs:
    image: false
    seg_gt: false
    seg: false
    seg_mask: false
    seg_opencities_mask: false
    seg_luxcarta: false
    crossfield: false
    uv_angles: false
    poly_shapefile: false
    poly_geojson: false
    poly_viz: false

  save_aggregated_outputs:
    stats: false
    seg_coco: false
    poly_coco: false
