name: hisup

defaults:
    - lidar_encoder: pointpillars

encoder:
    type: HRNet48v2
    pretrained: True
    checkpoint_file: ${...host.data_root}/hrnetv2_w48_imagenet_pretrained.pth

    in_size: 512
    in_height: ${.in_size}
    in_width: ${.in_size}
    
    out_feature_size: 128
    out_feature_height: ${.out_feature_size}
    out_feature_width: ${.out_feature_size}
    
    out_feature_channels: 256

lidar_encoder:
    # in theory, these are values in [m]. However, because I scale the LiDAR tile to match image coordinates, these are [m]*s, i.e. here s=224/56
    # in fact, one voxel is always 0.25m x 0.25m, so the standard voxel size is 2m x 2m
    in_voxel_size:
        x: 8
        y: 8

    max_num_points_per_voxel: 128 # this should be something around points_per_tile / num_voxels_per_tile, however, I find that half of that value is enough

    max_num_voxels: # (in_image_size / in_voxel_size)**2
        train: 4096
        test: 4096

    out_feature_width: ${..encoder.out_feature_width}
    out_feature_height: ${..encoder.out_feature_height}

    out_feature_channels: 64

# training
batch_size: 16
start_epoch: 0
num_epochs: 100
milestone: 0
learning_rate: 1e-4
weight_decay: 1e-4

loss_weights:
    loss_joff: 0.25    # joff  regression
    loss_jloc: 8.0     # jloc  classification
    loss_mask: 1.0
    loss_afm : 0.1
    loss_remask : 1.0

augmentations:
    - D4
    - Resize
    - ColorJitter
    - GaussNoise