name: hisup

defaults:
    - lidar_encoder: pointpillars_vit

encoder:
    type: HRNet48v2
    pretrained: True
    checkpoint_file: ${...host.data_root}/hrnetv2_w48_imagenet_pretrained.pth

    in_size: 512
    in_height: ${.in_size}
    in_width: ${.in_size}
    
    out_feature_size: 128
    out_feature_height: ${.out_feature_size}
    out_feature_width: ${.out_feature_size}
    
    out_feature_dim: 256


decoder:
    in_feature_dim: 256

# training
batch_size: 16
start_epoch: 0
num_epochs: 100
milestone: 0
learning_rate: 1e-4
weight_decay: 1e-4

loss_weights:
    loss_joff: 0.25    # joff  regression
    loss_jloc: 8.0     # jloc  classification
    loss_mask: 1.0
    loss_afm : 0.1
    loss_remask : 1.0

augmentations:
    - D4
    - Resize
    - ColorJitter
    - GaussNoise