[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ppp"
version = "0.1.0"
description = "Pixels, Points, Polygons: A Global Dataset and Baseline for Multimodal Building Vectorization"
authors = [
    { name = "Raphael Sulzer", email = "raphael.sulzer.1@gmail.com" }
]
dependencies = [
    "transformers==4.32",
    "pycocotools",
    "torchmetrics",
    "wandb",
    "timm",
    "matplotlib",
    "albumentations",
    "shapely",
    "hydra-core",
    "laspy[lazrs]",
    "colorlog",
    "descartes==1.1.0",
    "scikit-image",
    "scikit-learn"
]

[project.scripts]
ppp = "scripts:train"
