[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pixelspointspolygons"
version = "0.1.0"
description = "Pixels, Points, Polygons: A Global Dataset and Baseline for Multimodal Building Vectorization"
authors = [
    { name = "Raphael Sulzer", email = "raphael.sulzer.1@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "albumentations",
    "colorlog",
    "descartes==1.1.0",
    "hydra-core",
    "laspy[lazrs]",
    "matplotlib",
    "pandas",
    "pycocotools",
    "scikit-image",
    "scikit-learn",
    "shapely",
    "timm",
    "torchmetrics",
    "transformers==4.32",
    "wandb"
]


[tool.setuptools]
packages = ["pixelspointspolygons"]

[tool.setuptools.package-data]
pixelspointspolygons = ["conf/*.yaml"]