# Possible options: simple, acm, asm, tracing or a list to apply multiple methods
method: 
  - simple
  - acm
  # - asm
  # - tracing

common_params:
  init_data_level: 0.5  # Segmentation level to initialize contours for all methods

simple_method:
  data_level: 0.5  # Segmentation level to initialize contours
  tolerance: 
    - 0.125
    - 1  # List of values to apply
  seg_threshold: 0.5
  min_area: 10

asm_method:
  init_method: skeleton  # Can be either "skeleton" or "marching_squares"
  data_level: 0.5
  loss_params:
    coefs:
      step_thresholds: [0, 100, 200, 300]  # Gradual coefficient transitions
      data:         [1.0,  0.1,  0.0, 0.0]
      crossfield:   [0.0, 0.05,  0.0, 0.0]
      length:       [0.1, 0.01, 0.0, 0.0]
      curvature:    [0.0,  0.0,  1.0, 0.0]
      corner:       [0.0,  0.0,  0.5, 0.0]
      junction:     [0.0,  0.0,  0.5, 0.0]
    curvature_dissimilarity_threshold: 2  # Pixels: Threshold for optimizing straightness
    corner_angles: [45, 90, 135]  # Target angles for corners
    corner_angle_threshold: 22.5  # Angle threshold for corner optimization
    junction_angles: [0, 45, 90, 135]  # Target angles for junctions
    junction_angle_weights: [1, 0.01, 0.1, 0.01]  # Priority: straight > right-angle > 45°
    junction_angle_threshold: 22.5  # Angle threshold for junction optimization
  lr: 0.1
  gamma: 0.995
  device: "cuda"
  tolerance: 
      - 0.125
    # - 1  # List of values to apply
  seg_threshold: 0.5
  min_area: 10

acm_method:
  steps: 500
  data_level: 0.5  # Segmentation level for contour optimization
  data_coef: 0.1
  length_coef: 0.4
  crossfield_coef: 0.5
  poly_lr: 0.01
  warmup_iters: 100
  warmup_factor: 0.1
  device: "cuda"
  tolerance:
      - 0.125
      - 1  # List of values to apply
  seg_threshold: 0.5  # Remove polygons below this threshold
  min_area: 10