name: hrnet

use_images: true
use_lidar: false

type: HRNet48v2
pretrained: True
checkpoint_file: ${..host.data_root}/hrnetv2_w48_imagenet_pretrained.pth

in_size: 512
in_height: ${.in_size}
in_width: ${.in_size}

out_feature_size: 128
out_feature_height: ${.out_feature_size}
out_feature_width: ${.out_feature_size}

out_feature_dim: 256