name: vit_cnn

use_images: true
use_lidar: false

checkpoint_file: null # will load from official pretrained checkpoint
type: vit_small_patch${.patch_size}_${.in_size}.dino

in_size: 224
in_height: ${.in_size}
in_width: ${.in_size}

pretrained: True

patch_size: 8

patch_feature_size: 28
patch_feature_height: ${.patch_feature_size}
patch_feature_width: ${.patch_feature_size}

patch_feature_dim: 384


out_feature_size: ${..model.decoder.in_feature_size}
out_feature_height: ${.out_feature_size}
out_feature_width: ${.out_feature_size}

out_feature_dim: ${..model.decoder.in_feature_dim}


# ViT doesn't seem to need any normalization
image_mean: [0.0, 0.0, 0.0]
image_std: [1.0, 1.0, 1.0]
image_max_pixel_value: 255.0

augmentations:
    - D4
    # - Resize
    - ColorJitter
    - GaussNoise
    - Normalize