name: vit_dinov2

use_images: true
use_lidar: false

type: vit_small_patch${.patch_size}_${.in_size}.dino
checkpoint_file: ${..dataset.out_path}/backbones/dinov2_vits14_pretrain.pth
pretrained: True

# image/lidar input dimensions
in_size: 224
in_height: ${.in_size}
in_width: ${.in_size}

# patching
patch_size: 14
feature_map_size: 16 # this is for the LiDAR encoder and the transformer decoder = 224//8 = in_size//patch_size
feature_map_height: ${.feature_map_size}
feature_map_width: ${.feature_map_size}
patch_feature_dim: 384
num_patches: 256  # int((self.cfg.experiment.encoder.in_size // self.cfg.experiment.encoder.patch_size) ** 2)

out_feature_dim: ${..model.decoder.in_feature_dim}

# DINO v2 normalization
image_mean: [0.485, 0.456, 0.406]
image_std: [0.228, 0.224, 0.225]
image_max_pixel_value: 255.0

augmentations:
    - D4
    # - Resize
    - ColorJitter
    - GaussNoise
    - Normalize