defaults:
  - model: pix2poly   # Default model
  - dataset: lidarpoly   # Default dataset
  - run_type: release   # Default run_type
  - host: gin
  - _self_

# experiment_name: images_only
experiment_name: debug
# experiment_name: inria_D4_aug
# experiment_name: lidarpoly_ori_aug

multi_gpu: false

device: cuda
# checkpoint: /data/rsulzer/pix2poly_outputs/lidarpoly/${.experiment_name}/logs/checkpoints/epoch_49.pth
# checkpoint: /data/rsulzer/pix2poly_outputs/${.dataset.name}/${.experiment_name}/logs/checkpoints/validation_best.pth
checkpoint: null
output_dir: ${.host.data_root}/${.model.name}_outputs/${.dataset.name}/${.experiment_name}
log_to_wandb: ${.run_type.log_to_wandb}

model:
  batch_size: ${..run_type.batch_size}
dataset:
  subset: ${..run_type.subset}
num_workers: ${.run_type.num_workers}


use_lidar: true
use_images: true

debug_vis: false