name: pix2poly
encoder:
    input_size: 224
    input_height: ${.input_size}
    input_width: ${.input_size}
    type: vit_small_patch${.patch_size}_${.input_size}.dino
    patch_size: 8
    num_patches: null
    out_dim: 256
    pretrained: True

tokenizer: 
    num_bins: ${..encoder.input_size}
    shuffle_tokens: false
    n_vertices: 192
    max_len: null
    pad_idx: null
    generation_steps: null


# optimization
sinkhorn_iterations: 100
label_smoothing: 0.0
vertex_loss_weight: 1.0
perm_loss_weight: 10.0

# training
batch_size: 32
start_epoch: 0
num_epochs: 100
milestone: 0
val_every: 1
learning_rate: 4e-4
weight_decay: 1e-4

save_best: True
save_latest: True
save_every: 10