defaults:
  - host: gin
  - run_type: release
  - polygonization: asm_acm
  - dataset: lidarpoly
  - experiment: lidar_density_ablation4
  # - experiment: lidar_density_ablation4
  # - experiment: lidar_density_ablation64
  # - experiment: debug
  # - experiment: hisup
  # - experiment: ffl
  - _self_

hydra:
  run:
    dir: ${...output_dir}

output_dir: ${.host.data_root}/${.experiment.model.name}_outputs/${.dataset.name}/${.experiment.encoder.in_size}/${.experiment.name}

checkpoint: null
checkpoint_file: null

multi_gpu: false
device: cuda
log_to_wandb: ${.run_type.log_to_wandb}
num_workers: ${.run_type.num_workers}
update_pbar_every: ${.host.update_pbar_every}

country: Switzerland

dataset:
  train_subset: ${..run_type.train_subset}
  val_subset: ${..run_type.val_subset}
  size: ${..experiment.encoder.in_size}
  annotations:
    train: ${..path}/annotations_${...country}_train.json
    val: ${..path}/annotations_${...country}_val.json
    test: ${..path}/annotations_${...country}_test.json

experiment:
  model:
    batch_size: ${...run_type.batch_size}

use_lidar: ${.experiment.encoder.use_lidar}
use_images: ${.experiment.encoder.use_images}

save_best: true
save_latest: true
save_every: 10
val_every: 1
best_val_loss: 10000000.0
best_val_iou: 0.0

eval:
  gt_file: ${..dataset.annotations.test}
  pred_file: ${..output_dir}/predictions/${..checkpoint}.json
  # pred_file: ${..output_dir}/predictions/test.json
  modes:
    # - coco
    - iou
    # - polis
    # - mta
    # - stats
    # - topdig
  # eval_file: ${..host.data_root}/${..dataset.name}/metrics.csv
  eval_file: results/metrics






