defaults:
  - host: gin
  - run_type: release
  - dataset: p3
  - experiment: ffl_fusion
  - training: default
  # - experiment: ffl_image
  # - experiment: lidar_density_ablation256.yaml
  # - experiment: hisup_fusion
  # - experiment: p2p_fusion
  # - experiment: p2p_lidar
  - _self_

experiment.name: debug


hydra:
  run:
    dir: ${...output_dir}

# output_dir: ${.host.data_root}/${.experiment.model.name}_outputs/${.dataset.name}/${.experiment.encoder.in_size}/${.experiment.name}
output_dir: ${.host.model_root}/${.experiment.model.name}/${.experiment.encoder.in_size}/${.experiment.name}

checkpoint: null
# checkpoint: best_val_iou
# checkpoint: latest
checkpoint_file: null

log_to_wandb: ${.run_type.log_to_wandb}
num_workers: ${.run_type.num_workers}

# dataset:
#   size: 224015

eval:
  split: val # do not change this here, because it could cause that during training, test predictions are overwritten
  pred_file: ${..output_dir}/predictions_${..experiment.country}_${.split}/${..checkpoint}.json
  modes:
    - ldof
    # - hausdorff
    - coco
    - iou
    - polis
    - mta
    # - subset_iou
    # - stats
    # - topdig
  eval_file: results/metrics
  ldof_exe: /user/rsulzer/home/cpp/line-DOF-metric/build/calculate_DoF






