defaults:
  - encoder: hrnet
  # - encoder: pointpillars
  - model: hisup
  - dataset: lidarpoly
  - run_type: release
  - host: gin
  - _self_
hydra:
  run:
    dir: ${...output_dir}

output_dir: ${.host.data_root}/${.model.name}_outputs/${.dataset.name}/${.experiment_name}
checkpoint: null
# checkpoint_file: null # override for loading a specific checkpoint file not in the output_dir
# checkpoint_file: /data/rsulzer/hisup_outputs/lidarpoly_hisup_ori/v1_lidar_LROnP/model_best.pth
checkpoint_file: /data/rsulzer/hisup_outputs/lidarpoly_hisup_ori/v1_image_only_bs8/model_best.pth

experiment_name: debug
group_name: v2_${.model.name}
multi_gpu: false
device: cuda
log_to_wandb: ${.run_type.log_to_wandb}
num_workers: ${.run_type.num_workers}
debug_vis: true
update_pbar_every: ${.host.update_pbar_every}

dataset:
  train_subset: ${..run_type.train_subset}
  val_subset: ${..run_type.val_subset}
  size: ${..encoder.in_size}

model:
  batch_size: ${..run_type.batch_size}

use_lidar: ${.encoder.use_lidar}
use_images: ${.encoder.use_images}

save_best: true
save_latest: true
save_every: 10
val_every: 1

eval:
  gt_file: ${..dataset.annotations.val}
  pred_file: ${..output_dir}/predictions/${..checkpoint}.json
  # eval_file: ${..output_dir}/eval/${..checkpoint}.csv
  modes:
    # - coco
    - iou
    # - polis
    # - mta
    # - stats
    - topdig
  experiments:
    - model: ffl
      experiment_name: 
      - image_bs2x8
    - model: hisup
      experiment_name:
      - image_only_nogn_nocj_bs4x8
      - both_nogn_nocj_bs16
    - model: pix2poly
      experiment_name:
      - image_only_bs4x16
      - lidar_only_bs2x16
      - fusion_simple_bs4x32
  eval_file: ${..host.data_root}/metrics.csv






