defaults:
  - host: default
  - run_type: release
  - dataset: p3
  - experiment: null
  - training: default
  - evaluation: val
  # - experiment: ffl_image
  # - experiment: lidar_density_ablation256.yaml
  # - experiment: hisup_fusion
  # - experiment: p2p_fusion
  # - experiment: p2p_lidar
  - _self_

# experiment.name: debug

output_dir: ${.host.model_root}/${.experiment.model.name}/${.experiment.encoder.in_size}/${.experiment.name}

checkpoint: null

num_workers: ${.run_type.num_workers}

hydra:
  run:
    dir: ${...output_dir}




