name: pointpillars
max_num_points_per_voxel: 128 # this should be something around points_per_tile / num_voxels_per_tile
z_max: 100 # all pointclouds will be scaled to [0, lidar_height]
voxel_size:
  x: 8
  y: 8
  z: ${..z_max}