name: default
data_root: data/${..dataset.name}
model_root: data/${..dataset.name}_output

multi_gpu: false
device: cuda

update_pbar_every: 1

ldof_exe: /path/to/calculate_DoF

dino_v2_repo: /path/to/dinov2_repo