name: g5k
dataset_root: /home/rsulzer/data_group
model_root: /home/rsulzer/data_group

multi_gpu: true
device: cuda

update_pbar_every: 60

ldof_exe: null

dino_v2_repo: /home/rsulzer/python/dinov2
dino_v3_repo: /home/rsulzer/python/dinov3