name: gin
data_root: /data/rsulzer/${..dataset.name}_dataset
model_root: /data/rsulzer/${..dataset.name}_output

multi_gpu: false
device: cuda

update_pbar_every: 1

ldof_exe: /user/rsulzer/home/cpp/line-DOF-metric/build/calculate_DoF