name: gin
dataset_root: /data/rsulzer
model_root: /data/rsulzer

multi_gpu: false
device: cuda

update_pbar_every: 1

ldof_exe: /user/rsulzer/home/cpp/line-DOF-metric/build/calculate_DoF

dino_v2_repo: /user/rsulzer/home/remote_python/dinov2
