name: jeanzay
data_root: /linkhome/rech/genlgm01/uku93eu/data/${..dataset.name}_dataset
model_root: /linkhome/rech/genlgm01/uku93eu/data/${..dataset.name}_output

multi_gpu: true
device: cuda

update_pbar_every: 60

ldof_exe: null

dino_v2_repo: /linkhome/rech/genlgm01/uku93eu/python/dinov2