name: inria
path: ${host.data_root}/${.name}_coco_224_negAug
annotations:
  train: ${..path}/train/annotation.json
  val: ${..path}/val/annotation.json
  test: ${..path}/test/annotation.json
images:
  train: ${..path}/train/images/
  val: ${..path}/val/images/
  test: ${..path}/test/images/
lidar:
  train: null
  val: null
  test: null
subset: null