name: RoofGraphDataset
size: ${..experiment.encoder.in_size}
in_path: ${host.dataset_root}/${..dataset.name}
out_path: ${host.model_root}/${..dataset.name}_output
annotations:
  train: ${..in_path}/annotations/${...experiment.annotation_type}/annotations_train.json
  val: ${..in_path}/annotations/${...experiment.annotation_type}/annotations_val.json
  test: ${..in_path}/annotations/${...experiment.annotation_type}/annotations_test.json
train_subset: ${..run_type.train_subset}
val_subset: ${..run_type.val_subset}
test_subset: ${..run_type.test_subset}